# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

project 'DR_NewMedia.project'

inhibit_all_warnings!

target 'DR_NewMedia' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DR_NewMedia
pod ‘Masonry’

pod ‘SDWebImage’

pod 'MBProgressHUD'


end
